version: '3.8'

services:
  db:
    image: postgres:15
    container_name: appstore_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: appstore_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/appstore
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app

volumes:
  pgdata:
